import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const pleaseSub = api.subscribe.sub.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-2 text-white">
        <p>list od all notes</p>
        <Link
          className="inline-block rounded-lg bg-green-600 px-4 py-1 text-base font-semibold leading-7 shadow-sm ring-1 ring-green-600 hover:bg-green-700 hover:ring-green-700"
          href="/newnote"
        >
          Add Note
        </Link>
      </main>
    </>
  );
}
